# Generated by Django 5.1.4 on 2025-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytime',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
