# Generated by Django 5.1.4 on 2025-01-12 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_workpointrecord_delete_entrytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpointrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 12, 20, 16, 17, 79609, tzinfo=datetime.timezone.utc)),
        ),
    ]
