# Generated by Django 5.1.4 on 2025-01-12 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_alter_workpointrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpointrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
