# Generated by Django 5.1.4 on 2025-01-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0005_alter_workpointrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpointrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
