# Generated by Django 5.1.4 on 2025-01-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_alter_workpointrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpointrecord',
            name='type_point',
            field=models.CharField(choices=[('I', 'Entrada'), ('O', 'Saída')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='workpointrecord',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
