# Generated by Django 5.1.4 on 2025-01-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0007_alter_workpointrecord_type_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpointrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
